name: "7mind env action"
description: "Sets up 7mind environment"
author: "Septimal Mind"
branding:
  icon: "minimize"
  color: "blue"
inputs:
  java-vendor:
    description: "Java vendor, e.g. microsoft"
    default: "microsoft"
    required: false
  java-version:
    description: "Java version, e.g. 11"
    default: ""
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: rlespinasse/github-slug-action@v4
    - uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-vendor }}
        java-version: ${{ inputs.java-version }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.cache/coursier
          ~/.ivy2/cache
          /usr/local/bin/cs
        key: ${{ runner.os }}-scala
    - name: Install Coursier
      run: |
        if [[ ! -f /usr/local/bin/cs ]]; then
          sudo curl -Lo /usr/local/bin/cs  https://git.io/coursier-cli-linux
          sudo chmod +x /usr/local/bin/cs
        fi
