name: "7mind env action"
description: "Sets up 7mind environment"
author: "Septimal Mind"
branding:
  icon: "minimize"
  color: "blue"
inputs:
  java-enable:
    description: "Set up JDK"
    default: "true"
    required: false
  java-vendor:
    description: "Java vendor, e.g. microsoft"
    default: "microsoft"
    required: false
  java-version:
    description: "Java version, e.g. 11"
    default: "17"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: rlespinasse/github-slug-action@v4
    - uses: actions/setup-java@v3
      if: ${{ inputs.java-enable == "true" }}
      with:
        distribution: ${{ inputs.java-vendor }}
        java-version: ${{ inputs.java-version }}
    - uses: actions/cache@v3
      name: Cache (SBT, Coursier, Ivy)
      if: ${{ inputs.java-enable == "true" }}
      with:
        path: |
          ~/.sbt
          ~/.cache/coursier
          ~/.ivy2/cache
          /usr/local/bin/cs
        key: ${{ runner.os }}-scala
    - name: Install Coursier
      if: ${{ inputs.java-enable == "true" }}
      shell: bash
      run: |
        if [[ ! -f /usr/local/bin/cs ]]; then
          sudo curl -Lo /usr/local/bin/cs  https://git.io/coursier-cli-linux
          sudo chmod +x /usr/local/bin/cs
        fi
    - name: Set variables
      shell: bash
      run: |
          CI_BRANCH_TAG="$(git describe --contains | grep v | grep -v '~' | head -n 1 || true)"
          {
            echo "CI_BRANCH_TAG=${CI_BRANCH_TAG}"
            echo "CI=true"
            echo "CI_COMMIT=${GITHUB_SHA}"
            echo "CI_BUILD_UNIQ_SUFFIX=\"${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}.${GITHUB_RUN_ID}\""
          } >>"$GITHUB_ENV"


