name: "7mind env action"
description: "Sets up 7mind environment"
author: "Septimal Mind"
branding:
  icon: "minimize"
  color: "blue"
inputs:
  setup-nix:
    description: "Setup Nix"
    default: true
    required: false
  cache-scala:
    description: "Cache Scala artifacts"
    default: true
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: rlespinasse/github-slug-action@v4
    - name: Install Nix
      if: ! contains(runner.labels, 'nix') && ${{ inputs.setup-nix == 'true' }}
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cache Nix
      if: ! contains(runner.labels, 'nix') && ${{ inputs.setup-nix == 'true' }}
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Set variables
      shell: bash
      run: |
          {
            echo "LC_ALL=C.UTF-8"
            echo "CI_BRANCH=${GITHUB_REF_NAME}"
            echo "CI_COMMIT=${GITHUB_SHA}"
            echo "CI_BRANCH_TAG=$(git describe --contains | grep v | grep -v '~' | head -n 1 || true)"
            echo "CI=true"
            echo "CI_BUILD_UNIQ_SUFFIX=${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}.${GITHUB_RUN_ID}"
            echo "CI_PULL_REQUEST=${{ github.event_name == 'pull_request' }}"
          } >>"$GITHUB_ENV"
    - name: Configure git
      shell: bash
      run: |
          git config --global user.name "$USER"
          git config --global user.email "build+${GITHUB_RUN_ID}+${GITHUB_SHA}@github.actions"
          git config --global core.sshCommand "ssh -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          git config --global --get user.name
          git config --global --get user.email
    - uses: actions/cache@v4
      name: Cache (SBT, Ivy, Coursier)
      if: ${{ inputs.cache-scala == 'true' }}
      with:
        path: |
          ~/.sbt
          ~/.cache/coursier
          ~/.ivy2/cache
        key: ${{ runner.os }}-scala
